export {default as Navbar} from './Navbar/Navbar'
export {default as HomePageBody} from './HomePageBody/HomePageBody'
// export {default as InfoSection} from './InfoSection/InfoSection'
export {default as Footer} from './Footer/Footer'
// export {default as MainPageBody} from './MainPageBody/MainPageBody'
// export {default as HelpLayout} from './Layout/HelpLayout'
export {default as SubNavbar} from './Navbar/SubNavbar'
export {default as PdfGenerator} from './PDFgenerator/PdfGenerator'
export {default as GeneratePDF} from './PDFgenerator/GeneratePDF'
export {default as CreateText} from './MainPageBody/CreateText'
export {default as PageScreenPDF} from './PDFgenerator/PageScreenPDF'
export {default as ChooseTemplate} from './MainPageBody/ChooseTemplate'